name: json_to_xlsx

on:
  push:
    branches: [main]

jobs:
  Running_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v5

      - name: json_to_xlsx
        run: |
          pip install
          python json_to_xlsx.py